=== Starcloud-retro/BTECH-LAB-CODES/web_technologies/WT_LAB/week4/bookstore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Root element -->
  <xs:element name="bookstore">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="author" type="xs:string"/>
              <xs:element name="ISBN" type="xs:string"/>
              <xs:element name="publisher" type="xs:string"/>
              <xs:element name="edition" type="xs:positiveInteger"/>
              <xs:element name="price" type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Starcloud-retro/BTECH-LAB-CODES/web_technologies/wt_lab/week4/bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="bookstore.xsd">

  <book>
    <title>web programming</title>
    <author>chrisbates</author>
    <ISBN>123-456-789</ISBN>
    <publisher>wiley</publisher>
    <edition>3</edition>
    <price>350</price>
  </book>

  <book>
    <title>internet worldwideweb</title>
    <author>ditel&amp;ditel</author>
    <ISBN>123-456-781</ISBN>
    <publisher>person</publisher>
    <edition>3</edition>
    <price>450</price>
  </book>

</bookstore>
